// <auto-generated />
using System;
using System.Collections.Generic;
using AiAgentsTeam.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiAgentsTeam.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260724185226_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiAgentsTeam.Domain.Agents.AgentRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("Dependencies")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HealthCheck")
                        .HasColumnType("text");

                    b.Property<int>("InFlightTaskCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.PrimitiveCollection<List<string>>("Permissions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("ProducedArtifacts")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("RequiredContext")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("Skills")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.PrimitiveCollection<List<string>>("SupportedTasks")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("Tools")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("agent_registrations", (string)null);
                });

            modelBuilder.Entity("AiAgentsTeam.Domain.Artifacts.Artifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("OwnerAgent")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("PreviousVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StorageRef")
                        .HasColumnType("text");

                    b.Property<Guid?>("TaskNodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WorkflowRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PreviousVersionId");

                    b.HasIndex("WorkspaceId", "Name");

                    b.ToTable("artifacts", (string)null);
                });

            modelBuilder.Entity("AiAgentsTeam.Domain.Checkpoints.Checkpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowRunId");

                    b.ToTable("checkpoints", (string)null);
                });

            modelBuilder.Entity("AiAgentsTeam.Domain.Intent.ClarificationAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IntentSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IntentSessionId");

                    b.ToTable("clarification_answers", (string)null);
                });

            modelBuilder.Entity("AiAgentsTeam.Domain.Intent.IntentSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AmbiguitiesJson")
                        .HasColumnType("text");

                    b.Property<double?>("ComplexityScore")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtractedGoalsJson")
                        .HasColumnType("text");

                    b.Property<string>("ProjectClassification")
                        .HasColumnType("text");

                    b.Property<string>("RawInput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RiskFlagsJson")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("StructuredRequirementsArtifactId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("intent_sessions", (string)null);
                });

            modelBuilder.Entity("AiAgentsTeam.Domain.Memory.MemoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Layer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ScopeRef")
                        .HasColumnType("uuid");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("SourceArtifactId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SupersededById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("TtlAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Layer", "ScopeRef");

                    b.ToTable("memory_items", (string)null);
                });

            modelBuilder.Entity("AiAgentsTeam.Domain.Reasoning.ReasoningTrace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Agent")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("InputJson")
                        .HasColumnType("text");

                    b.Property<string>("OutputJson")
                        .HasColumnType("text");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("TaskNodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskNodeId", "Stage");

                    b.ToTable("reasoning_traces", (string)null);
                });

            modelBuilder.Entity("AiAgentsTeam.Domain.Supervisor.SupervisorDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("InputSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetNodeIdsJson")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowRunId");

                    b.ToTable("supervisor_decisions", (string)null);
                });

            modelBuilder.Entity("AiAgentsTeam.Domain.Workflow.TaskEdge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PredecessorNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SuccessorNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkflowRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PredecessorNodeId");

                    b.HasIndex("SuccessorNodeId");

                    b.HasIndex("WorkflowRunId");

                    b.ToTable("task_edges", (string)null);
                });

            modelBuilder.Entity("AiAgentsTeam.Domain.Workflow.TaskNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedAgentName")
                        .HasColumnType("text");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InputsJson")
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OutputsJson")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentNodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReasoningSummary")
                        .HasColumnType("text");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("boolean");

                    b.Property<string>("RiskLevel")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkflowRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowRunId", "Status");

                    b.ToTable("task_nodes", (string)null);
                });

            modelBuilder.Entity("AiAgentsTeam.Domain.Workflow.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("workflow_definitions", (string)null);
                });

            modelBuilder.Entity("AiAgentsTeam.Domain.Workflow.WorkflowRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WorkflowDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("workflow_runs", (string)null);
                });

            modelBuilder.Entity("AiAgentsTeam.Domain.Workspaces.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("AiAgentsTeam.Domain.Intent.ClarificationAnswer", b =>
                {
                    b.HasOne("AiAgentsTeam.Domain.Intent.IntentSession", null)
                        .WithMany("Answers")
                        .HasForeignKey("IntentSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiAgentsTeam.Domain.Workflow.TaskEdge", b =>
                {
                    b.HasOne("AiAgentsTeam.Domain.Workflow.WorkflowRun", null)
                        .WithMany("Edges")
                        .HasForeignKey("WorkflowRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiAgentsTeam.Domain.Workflow.TaskNode", b =>
                {
                    b.HasOne("AiAgentsTeam.Domain.Workflow.WorkflowRun", null)
                        .WithMany("Nodes")
                        .HasForeignKey("WorkflowRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiAgentsTeam.Domain.Intent.IntentSession", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("AiAgentsTeam.Domain.Workflow.WorkflowRun", b =>
                {
                    b.Navigation("Edges");

                    b.Navigation("Nodes");
                });
#pragma warning restore 612, 618
        }
    }
}
